
```{r}
rm(list = ls())
setwd(
  "C:/Users/GabrielNascimento/Documents/Gabriel/UFMG25-2/reg/trabalho_final"
)

library(glmnet)
library(tidyverse)
library(dplyr)
library(sf)

borders_sf = st_read("data/world-administrative-boundaries.kml") |>
  select(-Description)
abreviations = rio::import("data/abreviations.csv")

hap_path = "data/happines_idx/"
happines_list = lapply(paste0(hap_path, list.files(hap_path)), rio::import)
happines_df = happines_list[[1]]


```

```{r Tratamento}
# TODO:
# - [ ] Filtrar os países que não ocorrem todos os anos

# Todos numéricos menos país, NA entra na última col pq tem uma str "N/A"
happines_df = happines_df |> mutate(across(-c(1, 2), as.numeric))
names(happines_df) = c(
  "Country", # "Country"
  "Region", # "Region"
  "Rank", # "Happiness Rank"
  "Score", # "Happiness Score"
  "StdErr", # "Standard Error"
  "GDP", # "Economy (GDP per Capita)"
  "Family", # "Family"
  "LifeExp", # "Health (Life Expectancy)"
  "Freedom", # "Freedom"
  "Trust", # "Trust (Government Corruption)"
  "Generosity", # "Generosity"
  "Dystopia_Res" # "Dystopia Residual"
)

selectedBorders_sf = borders_sf |>
  inner_join(abreviations, by = "Name") |>
  mutate(Country = gsub("\\(.*", "", Country)) |>
  inner_join(happines_df, by = "Country")


plot(selectedBorders_sf[, c("Score", "geometry")])

# # Estamos perdendo muitas linhas no join entre as borders e as abreviações
# setdiff(happines_df$Country, selectedBorders_sf$Country)
# setdiff(selectedBorders_sf$Country, happines_df$Country)

# # Problema no merge em selectedBorders mergendo com happines_df foi resolvido no excell
# setdiff(borders_sf$Name, abreviations$Name)
# setdiff(abreviations$Name, borders_sf$Name)
```


```{r Visualização_e_estudo}
# TODO:
# - [ ] Visualização da alteração anual do índice
# - [ ] Matriz de correlação das covars
# - [ ] Relação entre as variáveis

```


```{r Modelagem}
# TODO:
# - [ ] Seleção das covars (lasso?)
# - [ ] Criação do modelo

```


```{r Visualização dos dados}
# TODO:
# - [ ] Mostrar coeficientes e resultados do modelo
# - [ ] Correlação espacial (opt.)

```


```{r Conclusão}
# TODO:
# - [ ] Mostrar como ocorrências afetaram o índice com o tempo
# - [ ] Como vamos mostrar os dados?

```